name: craftFlowers
main: cm.ptks.craftflowers.CraftFlowers
version: ${project.version}
author: patrykss & MenschenToaster
api-version: 1.16
website: https://github.com/MenschenToaster/CraftFlowers
commands:
  craftflowers:
    description: craftFlowers command description
    aliases: [craftf, cf]
depend:
  - FastAsyncWorldEdit