name: craftFlowers
main: cm.ptks.craftflowers.CraftFlowers
version: 0.4
author: patrykss
api-version: 1.16
website: https://twitter.com/_patryks
commands:
  craftflowers:
    description: craftFlowers command description
    aliases: [craftf, cf]